// src/data/vehicleCatalogs.js

export const catalogs = {
    1: { // Carros
      Audi: ["A1", "A3", "A4", "A5", "Q2", "Q3", "Q5", "Q7", "Otro"],
      Baic: ["X25", "X35", "X55", "BJ40", "Otro"],
      BMW: ["Serie 1", "Serie 2", "Serie 3", "Serie 4", "Serie 5", "X1", "X3", "X5", "X7", "Otro"],
      Changan: ["Alsvin", "CS15", "CS35", "CS75", "Otro"],
      Citroen: ["C-Elysée", "C3", "C4 Cactus", "C5 Aircross", "Otro"],
      Chery: ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Otro"],
      Chevrolet: ["Camaro", "Captiva", "Equinox", "Joy", "Onix", "Spark GT", "Tracker", "Traverse", "Tahoe", "Otro"],
      Fiat: ["Argo", "Cronos", "Mobi", "500", "Otro"],
      Ford: ["Edge", "Ecosport", "Escape", "Expedition", "Explorer", "Fiesta", "Focus", "Mustang GT", "Ranger", "Otro"],
      Haval: ["H2", "H6", "H9", "Otro"],
      Hyundai: ["i20", "Creta", "Elantra", "HB20", "Ioniq", "Grand i10", "Kona", "Palisade", "Santa Fe", "Staria", "Tucson", "Otro"],
      Honda: ["Brio", "City", "Civic", "HR-V", "CR-V", "Pilot", "Otro"],
      JAC: ["S2", "S3", "S5", "T6", "Otro"],
      Jaguar: ["I-Pace", "F-Pace", "F-Type", "Otro"],
      Jeep: ["Compass", "Cherokee", "Grand Cherokee", "Renegade", "Wrangler", "Otro"],
      Kia: ["Cerato", "Picanto", "Rio", "Seltos", "Sorento", "Sportage", "Telluride", "Otro"],
      "Land Rover": ["Discovery", "Defender", "Ranger Rover", "Ranger Rover Evoque", "Otro"],
      Maserati: ["Grecale", "Ghibli", "Levante", "Quattroporte", "Gran Turismo", "MC20", "Otro"],
      Mazda: ["Mazda 2", "Mazda 3", "Mazda 6", "CX-3", "CX-30", "CX-5", "CX-9", "Otro"],
      "Mini Cooper": ["Countryman", "C Favoured", "SE Hatch Iconic", "S-JCW SportPack", "SE Hatch Classic", "Otro"],
      Mitsubishi: ["ASX", "Lancer", "Mirage", "Montero Sport", "Outlander", "Otro"],
      "Mercedes-Benz": ["Clase A", "Clase B", "Clase C", "Clase E", "Clase G", "GLA", "GLC", "GLE", "GLS", "Otro"],
      "MG (Morris Garages)": ["MG3", "MG5", "MG6", "ZS", "HS", "Otro"],
      Nissan: ["Frontier", "Kicks", "March", "Pathfinder", "Qashqai", "Sentra", "Versa", "X-Trail", "Otro"],
      Peugeot: ["208", "2008", "3008", "5008", "Otro"],
      Ram: ["700 SLT", "700 Bighorm", "1500 DT", "V700 Rapid", "Otro"],
      Renault: ["Duster", "Koleos", "Kwid", "Logan", "Megane", "Sandero", "Stepway", "Zoe", "Otro"],
      Seat: ["Arona", "Ibiza", "Otro"],
      Scoda: ["Fabia", "KodiaQ", "Octavia", "Jeti", "Otro"],
      Subaru: ["Forester", "Impreza", "Outback", "XV", "Otro"],
      Suzuki: ["Alto", "Baleno", "Fronx", "Jimny", "Swift", "S-Cross", "S-Presso", "Vitara", "Otro"],
      Toyota: ["Corolla", "Corolla Cross", "Fortuner", "Hilux", "Land Cruiser", "Prado", "RAV4", "Yaris", "Otro"],
      Volkswagen: ["Gol", "Jetta", "Polo", "Nivus", "Teramont", "Tiguan", "T-Cross", "Virtus", "Otro"],
      Volvo: ["940", "960", "C30", "S60", "V40", "XC40", "XC60", "XC90", "Otro"],
      Otra: ["Otro"],
    },
    2: { // Motos
      AKT: ["Dynamic Pro", "CR4 125", "NKD 125", "RTX 150", "TTR 200", "Otro"],
      Auteco: ["KTM Duke 200", "Kawasaki Ninja ZX-10R", "Kawasaki Z900", "Starker Cargo", "Victory One", "Otro"],
      Bajaj: ["Boxer CT100", "Discover 125", "Dominar 400", "Pulsar NS160", "Pulsar 200NS", "Otro"],
      "BMW Motorrad": ["G 310 R", "F 750 GS", "K 1600 B", "R 1250 GS", "S 1000 RR", "Otro"],
      Ducati: ["Diavel 1260", "Monster 821", "Multistrada 950", "Panigale V2", "Scrambler Icon", "Otro"],
      "Harley-Davidson": ["Fat Boy", "Forty-Eight", "Iron 883", "Road King", "Street Bob", "Otro"],
      Hero: ["Glamour 125", "HF Deluxe", "Hunk 160R", "Splendor Plus", "Xpulse 200", "Otro"],
      Honda: ["CB125F", "CB190R", "CBR250R", "NC750X", "XR150L", "Otro"],
      Kawasaki: ["KLX 150BF", "Ninja 300", "Versys-X 300", "Vulcan S", "Z650", "Otro"],
      KTM: ["Adventure 390", "Duke 200", "Duke 390", "RC 200", "RC 390", "Otro"],
      "Royal Enfield": ["Classic 350", "Himalayan", "Meteor 350", "Bullet 350", "Interceptor 650", "Otro"],
      Suzuki: ["DR200S", "Gixxer 150", "GN125", "GSX-R150", "V-Strom 250", "Otro"],
      TVS: ["Apache RTR 160", "Jupiter", "Ntorq 125", "RR 310", "Star City Plus", "Otro"],
      Yamaha: ["BWS", "FZ25", "MT-03", "R3", "XTZ 125", "YBR 125", "Otro"],
    },
    3: { // Bicis
      Treck: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Cliff: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      "GW Bicycles": ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Specialized: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Giant: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Scott: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Orbea: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Liv: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Bianchi: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Venzo: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Optimus: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Roca: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Cube: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
      Marin: ["Montaña", "Ruta", "Urbana", "Eléctrica"],
    }
  };
  